"""Battery simulation figures and ``reports/battery.md``."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd

from elecprice.battery.simulate import STRATEGIES, STRATEGY_LABELS

COLORS = {
    "perfect_foresight": "#1b1b1b",
    "forecast_lgbm": "#2a6fdb",
    "forecast_naive": "#9a9a9a",
    "naive_fixed": "#d9822b",
}


def fig_cumulative(daily: pd.DataFrame, path: Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 3.6))
    for strategy in STRATEGIES:
        g = daily[daily["strategy"] == strategy].sort_values("settlement_date")
        ax.plot(
            pd.to_datetime(g["settlement_date"]),
            g["net_gbp"].cumsum() / 1000,
            color=COLORS[strategy],
            lw=1.6 if strategy == "forecast_lgbm" else 1.1,
            label=STRATEGY_LABELS[strategy],
        )
    ax.set_ylabel("Cumulative net £k (1 MW / 2 MWh)")
    ax.set_title("Battery arbitrage: cumulative net revenue by strategy")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(alpha=0.25)
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(path, dpi=110)
    plt.close(fig)


def fig_example_day(schedules: pd.DataFrame, daily: pd.DataFrame, path: Path) -> str:
    day = daily["settlement_date"].max()
    s = schedules[schedules["settlement_date"] == day]
    lg = s[s["strategy"] == "forecast_lgbm"].sort_values("start_time_utc")
    pf = s[s["strategy"] == "perfect_foresight"].sort_values("start_time_utc")
    t = (
        pd.to_datetime(lg["start_time_utc"])
        .dt.tz_localize("UTC")
        .dt.tz_convert("Europe/London")
        .dt.tz_localize(None)
    )
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 5), sharex=True)
    ax1.plot(t, lg["actual_price"], color="black", lw=1.1, label="Actual MID")
    ax1.plot(t, lg["decision_price"], color=COLORS["forecast_lgbm"], lw=1.1, label="P50 forecast")
    ax1.set_ylabel("£/MWh")
    ax1.legend(frameon=False, fontsize=8)
    ax1.set_title(f"Example day {pd.Timestamp(day):%a %d %b %Y}: prices and schedules")
    ax2.step(
        t,
        lg["discharge_mw"] - lg["charge_mw"],
        where="post",
        color=COLORS["forecast_lgbm"],
        label="Forecast-driven",
    )
    ax2.step(
        t,
        pf["discharge_mw"] - pf["charge_mw"],
        where="post",
        color=COLORS["perfect_foresight"],
        ls="--",
        lw=1,
        label="Perfect foresight",
    )
    ax2.axhline(0, color="grey", lw=0.6)
    ax2.set_ylabel("Net export MW (+ discharge)")
    ax2.legend(frameon=False, fontsize=8)
    ax2.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
    ax2.set_xlabel("UK local time")
    for ax in (ax1, ax2):
        ax.grid(alpha=0.25)
        ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(path, dpi=110)
    plt.close(fig)
    return str(pd.Timestamp(day).date())


def write_report(out_dir: Path, report_path: Path, fig_dir: Path) -> None:
    daily = pd.read_parquet(out_dir / "daily.parquet")
    schedules = pd.read_parquet(out_dir / "schedules.parquet")
    summary = pd.read_csv(out_dir / "summary.csv").set_index("strategy")
    params = json.loads((out_dir / "params.json").read_text())
    fig_dir.mkdir(parents=True, exist_ok=True)
    fig_cumulative(daily, fig_dir / "battery_cumulative.png")
    example = fig_example_day(schedules, daily, fig_dir / "battery_example_day.png")

    rows = []
    for st in STRATEGIES:
        r = summary.loc[st]
        rows.append(
            f"| {STRATEGY_LABELS[st]} | £{r['net_gbp']:,.0f} | £{r['net_gbp_per_mw_year']:,.0f} "
            f"| {r['capture_vs_perfect']:.1%} | {r['share_of_gap_closed']:.1%} "
            f"| {r['cycles_per_day']:.2f} |"
        )
    table = "\n".join(rows)
    monthly = daily.assign(month=pd.to_datetime(daily["settlement_date"]).dt.strftime("%Y-%m"))
    monthly = monthly.pivot_table(
        index="month", columns="strategy", values="net_gbp", aggfunc="sum"
    )
    mrows = "\n".join(
        f"| {m} | " + " | ".join(f"{monthly.loc[m, st]:,.0f}" for st in STRATEGIES) + " |"
        for m in monthly.index
    )
    lg, nv = summary.loc["forecast_lgbm"], summary.loc["forecast_naive"]
    uplift = (lg["net_gbp"] - nv["net_gbp"]) / summary.loc["forecast_lgbm", "days"] * 365
    start, end = daily["settlement_date"].min(), daily["settlement_date"].max()

    text = f"""# Battery arbitrage simulation

_Generated by `elec simulate`. {int(lg["days"])} delivery days,
{pd.Timestamp(start):%Y-%m-%d} to {pd.Timestamp(end):%Y-%m-%d}: every day of the
walk-forward backtest with settled prices._

## What is being simulated

A merchant battery trades the GB Market Index Price. Each day it commits to a
half-hourly charge and discharge schedule at the 09:00 D-1 cutoff and is paid
the actual price. Four strategies share the same asset and constraints:

- **Perfect foresight:** optimises on the actual prices. No strategy can beat
  this; it is the upper bound.
- **LightGBM P50 forecast:** optimises on the out-of-sample P50 forecast from
  the walk-forward backtest.
- **Seasonal naive forecast:** optimises on "same half-hour last week".
- **Fixed rule:** price-blind. It charges 01:00-05:00 and discharges
  16:30-19:30 UK time every day; this is the lower bound.

Schedules come from a linear programme (pulp + HiGHS, `battery/optimise.py`).
Settlement is a separate function: schedules only ever see decision prices.

| Parameter | Value |
|---|---|
| Power | {params["power_mw"]} MW |
| Usable energy | {params["energy_mwh"]} MWh |
| Round-trip efficiency | {params["round_trip_efficiency"]:.0%} (half the loss each way) |
| State of charge | starts and ends each day at {params["initial_soc_frac"]:.0%} |
| Cycle limit | {params["max_cycles_per_day"]} full-equivalent cycles per day |
| Degradation cost | £{params["degradation_cost_gbp_per_mwh"]:.0f} per MWh discharged |

## Results

| Strategy | Net £ | Net £/MW/yr | Share of perfect foresight | Share of gap closed | Cycles/day |
|---|---|---|---|---|---|
{table}

"Share of gap closed" places each strategy between the fixed rule (0%) and
perfect foresight (100%).

The forecast-driven battery earns **{lg["capture_vs_perfect"]:.0%} of the
perfect-foresight revenue**. That is £{lg["net_gbp"]:,.0f}, against
£{nv["net_gbp"]:,.0f} when scheduling on the naive forecast. The better forecast
is worth about **£{uplift:,.0f} per MW per year** on this asset, before any
other revenue stream.

![Cumulative revenue](figures/battery_cumulative.png)

The example below is the latest settled day ({example}): the forecast
schedule against the perfect-foresight one.

![Example day](figures/battery_example_day.png)

## Monthly net revenue (£)

| Month | {" | ".join(STRATEGY_LABELS[s] for s in STRATEGIES)} |
|---|---|---|---|---|
{mrows}

## Caveats

- **Price taker with perfect liquidity at MID.** Real day-ahead positions clear
  in auctions (not free data) and move the price slightly. MID is a proxy.
- **Wholesale arbitrage only.** No Balancing Mechanism, ancillary services or
  capacity market income, which dominate real GB battery revenues. The numbers
  are the value of *forecast-driven day-ahead arbitrage*, not a full business
  case.
- **Days are independent.** State of charge resets daily, so overnight
  positions spanning two delivery days are not optimised.
- **Degradation is linear in throughput.** This is a common simplification;
  real degradation also depends on depth of discharge, temperature and C-rate.
- **The optimiser uses the P50 only.** A risk-aware schedule that also uses the
  P10/P90 is a natural extension.
"""
    report_path.write_text(text)
